### ISSUE TITLE
Reaper feature request for fx

### ISSUE THREAD

**Issue by goldfingas** [nvaccess/osara#43] opened 2015-09-28 19:11 UTC
Hello. I have a question.
>> Is there a way to move fx around in a chain besides cutting and pasting them? I don't 
>> mind that, but you have to sometimes do tricks to get things where 
>> you want them.
>> I usually save chains when I get them the way I want them for later 
>> use, but was just wondering if we had some hotkey that I was missing 
>> out on.
>> Something like move selected fx up or down in the chain. If not, that 
>> would be a cool feature to add..
Thanks.

GF
>>

**Comment by jcsteh** [comment] 2015-09-29 08:09
This is fairly tricky to implement. However, it looks like the SWS extension already provides this: "SWS/S&M: Move selected FX up in chain for selected tracks" and "SWS/S&M: Move selected FX down in chain for selected tracks". The problem is that you can't bind actions for the FX window, so right now, you have to open the FX window, select the effect you want to move, push focus back to the main REAPER window without closing the FX window (which is tricky for some screen reader users) and then trigger the action. I *might* be able to find a way to force a hard-coded key binding into the FX window which triggers this action, but it's a big might.

In the interim, one trick I just discovered to force focus to the main window without closing the FX window is to press control+f4. That will get caught by the main window and will ask you if you want to save the project. When you press no, you're back in the main window. You can also move focus with NVDA object navigation if you're using NVDA, though that requires some pretty good familiarity with that concept.

**Comment by goldfingas** [comment] 2015-09-29 12:16
Well thanks for even looking in to it. You rock!

And I will have to give this a try. I’m sure you can come up with something. You are good at what you do..

**Comment by goldfingas** [comment] 2015-09-29 12:18
Can’t I just be listening to the project while I move the fx around? Then when I get it to where I want, just close the fx window? Or does it not work in real time?

**Comment by jcsteh** [comment] 2015-09-29 12:45
As I said, that depends on whether I can manage to hack a way to bind 
keystrokes into the FX window. REAPER doesn't actually allow you to bind 
actions to the FX window itself. That's why returning to the main window 
is necessary for now.

Once you're in the main window, sure, you can listen to the project 
while you move stuff around I guess. I'm actually not sure how well that 
will work.

**Comment by goldfingas** [comment] 2015-09-29 13:00
Ah, ok. I understand. Thanks.

**Comment by goldfingas** [comment] 2015-09-29 13:08
Maybe we can put in a feature request to the developers of reaper to maybe make it so that we can work in the fx window? Would that be something we can do, or do you think that’s too much to ask? I am not a programmer, so I don’t know what it would take to get this done.

**Comment by jcsteh** [comment] 2015-09-29 13:16
We could, but IMO, there are far more important things we need that have 
been requested and still aren't implemented, so I'd rather not throw any 
more out personally.

Btw, I did a bit of very quick experimentation and it seems I *can* at 
least capture keystrokes in the FX window, so I should be able to manage 
something, if inelegantly.

**Comment by goldfingas** [comment] 2015-09-29 13:21
I understand that. Although, I hope it doesn’t get forgotten about. I think the fx window is just as important as everything else. It takes all this stuff working together to make magic happen. Lol. But I would like to see more done with midi and other stuff as well, so I will wait in line patiently.

I just love the progress we have made with this thing in the last year or so. Keep the goodies coming!

And thank you for your help and continued work on this project.

**Comment by goldfingas** [comment] 2015-09-29 13:23
See? I told you that you would come up with something. Lol. The genius brain at work!

**Comment by chrisbelle2015** [comment] 2015-09-30 00:19
Just tried it with the control f4 method, works great.

**Comment by GianlucaApollaro** [comment] 2015-09-30 08:32
Hy guys. I actually don't need to do any trick to make them work. I just go to the fx list, select the one I want to move and use the sws action and the fx just moves. I don't need to bring the focus anywhere. If fx are bridged I need to get back to the fx list, but not to the main window

**Comment by goldfingas** [comment] 2015-09-30 13:47
Same here, it just works! Woohoo! Lovin it!

**Comment by jcsteh** [comment] 2015-09-30 13:58
Err, yeah, right. My sincere apologies. I was trying another action that, for various reasons, doesn't work in the FX window and assumed this meant all bindings don't work in the FX window.

I'm closing this then because SWS has an action that does everything you need and i see no need for duplicatino fo effort in this case.

**Closed by jcsteh** 2015-09-30 13:58 UTC
Labels: wontfix

**Comment by goldfingas** [comment] 2015-09-30 17:23
Thank you for the help.
