### ISSUE TITLE
Pressing tab key to report current focused window / tab in Reaper

### ISSUE THREAD

**Issue by charadani** [nvaccess/osara#123] opened 2017-08-23 21:29 UTC
Currently, when several projects / subprojects are opened and user presses CTRL+Tab keys, nothing is spoken by Osara with regards to the window/tab that gets focused.

Steps to reproduce:
1. Open a reaper project.
2. Create a new subproject with several items/tracks on it by pressing Alt+Shift+u.
3. CTRL+Tab cycling from the newly created tab to the original project tab.

The current behaviour requires that the user presses Insert+t to hear the tab title (which Osara renders beautifully at the time).

The expected behaviour, in my opinion, is that just when focus lands on the new tab, Osara will announce it straight away as if we were dealing with tabs within an Internet Browser or a native multi-tab windows control.

**Comment by jcsteh** [comment] 2017-08-23 21:46
Duplicate of #93.

**Closed by jcsteh** 2017-08-23 21:46 UTC
