### ISSUE TITLE
Options in send menu triggered via applications key on delete button no longer working

### ISSUE THREAD

**Issue by GianlucaApollaro** [nvaccess/osara#127] opened 2017-11-03 15:32 UTC
in latest version of reaper, v5.61 - October 27 2017, when hitting the apps key on the delete button of a send, the menu pops up, but the options have no effect on the selected send.
The only line in the changelog that refers to routing window changes is:
  + Routing window: fix potential crash with multiple windows open [t=192805]

**Comment by jcsteh** [comment] 2017-11-04 11:47
Confirmed. This is a bug in REAPER that I can't work around.

Technical: The IAccessible objects for the send controls now return an
accLocation of (0, 0, 0, 0), so we can't get their coordinates to click
them. I tried accDoDefaultAction, which was implemented a while back, but
this doesn't work either, probably because it internally uses the same
location information.

**Comment by ScottChesworth** [comment] 2017-11-04 13:21
Thanks for investigating Jamie. Is this something you'll have time to
pass along to Justin, or should we open a ticket on the bug tracker?
Seems like the former might get a fix quicker, but I don't know how
much time you have at the moment.

Let us know what's best.

**Comment by jcsteh** [comment] 2017-11-04 13:37
Already flicked Justin an email. However, I'm heading overseas on Monday for a week for work, so I probably won't have time to follow up on any developments until I get back and catch up on things.

**Comment by jcsteh** [comment] 2017-11-04 13:40
Oh. Justin already replied. He found the issue and is working on a fix. It'd be great if someone else can keep an eye on the pre-release changelog and builds and confirm whether this is fixed once it lands, as that'll save me the work. :)

**Comment by ScottChesworth** [comment] 2017-11-04 18:12
Gianluca is monitoring that. Hot diggity dang, things happen fast in Reaperland.

**Comment by chrisbelle2015** [comment] 2017-11-04 18:33
I know, isn't it unusually refreshing?

We get years of excuses and nothing happening with other companies but 
cockos really seems to care about our needs.
All it takes is one or two people  who can make all the difference.

I realize why some programs can't just be re-written all the time from 
the ground up just to satisfy our small market,
but I guess the nature of reaper makes it easier to do UI tweaks,
anyway, the whole attitude and the way cockos operates is so much a 
wonderful throw back to a better time in the software universe.

**Comment by jcsteh** [comment] 2017-11-04 22:31
I'm told this is now fixed in 5.65pre9. Would someone mind verifying?

**Comment by GianlucaApollaro** [comment] 2017-11-04 22:53
I confirm, 5.65pre9 solves it.

**Comment by jcsteh** [comment] 2017-11-05 02:20
Okay. Closing, since this is fixed in the REAPER code. Note that there may be a 5.62 release in the next week or so which includes this fix, but no promises.

**Closed by jcsteh** 2017-11-05 02:20 UTC
Labels: needs REAPER fix
