### ISSUE TITLE
Focus change bug when nudging volume of master track

### ISSUE THREAD

**Issue by ScottChesworth** [nvaccess/osara#77] opened 2016-02-21 23:55 UTC
Steps to reproduce:
1. Make your master track visible.
2. Create a new track.
3. Whilst focused on your new track, invoke either Track: nudge master volume up or Track: nudge master volume down.
4. Rinse and repeat without master track visible.

In both scenarios here, the focus jumps when these actions are triggered, and it shouldn't. When the master track is visible, focus is reset to be on that master track. Without the master track being visible things get a little more random, but I'm usually refocused on either track 1 or in no man's land above it.

Anything that can be done to prevent this?

**Comment by jcsteh** [comment] 2016-02-22 00:07
This is a REAPER issue, but arguably, it's intentional on their part. Basically, after you mess with the master volume, REAPER reports (at least via the API) that the last touched track is the master. I guess that kinda makes sense; it was the last track you "touched".

I guess this isn't what users will expect, but I'm always dubious about overriding behaviour that was intended by the app. It's also going to be a bit tricky to fix--I'm basically going to have to fight with REAPER--but I'll see what I can do.

**Comment by ScottChesworth** [comment] 2016-02-22 00:30
Sure, if you've actually moved a mouse to grab and drag a fader then
the master track is indeed the last thing you touched, but I think
this being the case with actions triggered via the API is a dodgy bit
of UX from them. Shout if it gives you major fits to hack around it
and I'll attempt to argue the case with Cockos hq instead.

**Comment by jcsteh** [comment] 2016-02-22 00:47
Those master volume actions are internal REAPER actions; we're not even 
triggering them from the API. Just to be sure, see if you can check if 
they screw with the last touched track with OSARA removed. If so, I'd 
suggest first tackling Cockos about this, since it's surely got to annoy 
sighted keyboard users as well. If Cockos refuse to play ball, I'll try 
to hack around it.

**Comment by ScottChesworth** [comment] 2016-02-22 01:01
Oki doke, I'll verify and attempt to reach Cockos.

**Comment by jcsteh** [comment] 2016-02-26 04:35
After some dialog with Cockos, this is fixed in REAPER 5.20pre11.

**Closed by jcsteh** 2016-02-26 04:35 UTC

**Comment by chrisbelle2015** [comment] 2016-02-26 07:49
Nice.
