### ISSUE TITLE
make toggling of master track mono or stereo talk

### ISSUE THREAD

**Issue by chrisbelle2015** [nvaccess/osara#115] opened 2017-03-23 01:35 UTC
I know we can listen sometimes and determine this but I keep finding I want to know immediately if the master track is mono or stereo and it is not always possible when working with center panned single sources. It would be wonderful to have this in place and spoken when toggled.
Thank you.

**Comment by jcsteh** [comment] 2017-03-23 02:14
Duplicate of #94.

**Closed by jcsteh** 2017-03-23 02:14 UTC
